dist: xenial
sudo: required
language: java
jdk:
  - openjdk8
  - openjdk11

# TODO split tests into mongo related & non mongo related. Run the former once.
env:
  - MONGODB_VER=mongodb-linux-x86_64-2.6.12 MINIO=2019-05-23T00-29-34Z ANT_TEST=test_quick_coverage WIRED_TIGER=false
  - MONGODB_VER=mongodb-linux-x86_64-3.6.10 MINIO=2019-05-23T00-29-34Z ANT_TEST=test_quick_coverage WIRED_TIGER=false
  - MONGODB_VER=mongodb-linux-x86_64-3.6.10 MINIO=2019-05-23T00-29-34Z ANT_TEST=test_quick_coverage WIRED_TIGER=true

before_install:
  # apt update fails without this key
  - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

  # install ant deps
  - sudo apt install -y ant-optional

  # install python deps
  - pyenv versions
  - export PYVER=$(pyenv versions | grep "3.7")
  - echo $PYVER
  - pyenv local $PYVER
  - python --version
  - pip3 install pipenv

install:
  - export HOMEDIR=`pwd`
  
  # set up jars
  - cd ..
  - git clone https://github.com/kbase/jars
  - export JARSDIR=`pwd`/jars/lib/jars/

  # set up arango
  - export ARANGODB_VER=3.5.1
  - export ARANGODB_V=35
  - curl -O https://download.arangodb.com/arangodb$ARANGODB_V/Community/Linux/arangodb3-linux-$ARANGODB_VER.tar.gz
  - tar -xf arangodb3-linux-$ARANGODB_VER.tar.gz 
  - export ARANGO_EXE=$(pwd)/arangodb3-$ARANGODB_VER/usr/sbin/arangod
  - export ARANGO_JS=$(pwd)/arangodb3-$ARANGODB_VER/usr/share/arangodb3/js/

  # set up handle service
  - export HS_COMMIT=aae2f70120e75d2ccccab1b1c01dbb9e8327eee8
  - export LOG_COMMIT=b549c557e3c519e0a55eadf7863a93db25cd6806
  - git clone https://github.com/kbase/handle_service2.git
  - cd handle_service2/
  - git checkout $HS_COMMIT
  - sudo chmod -R 777 .
  - cd lib/
  - mkdir biokbase
  - cd biokbase/
  - wget https://raw.githubusercontent.com/kbase/sdkbase2/$LOG_COMMIT/log.py
  - cd ..
  - export HSDIR=`pwd`
  - cd ../..
  
  # set up sample service
  - export SAMPLE_COMMIT=695bb800cb3babe2084e93c260affcd10018d3e7
  - git clone https://github.com/kbase/sample_service.git
  - cd sample_service
  - git checkout $SAMPLE_COMMIT
  - cd lib
  - export SAMPLE_DIR=`pwd`
  - cd ../..
  
  - cd $HOMEDIR
  
  # install python dependencies
  - cd python_dependencies
  - pipenv install --dev
  - cd ..

script:
  # set up minio
  - cd ..
  - wget https://dl.minio.io/server/minio/release/linux-amd64/archive/minio.RELEASE.$MINIO -O minio
  - chmod a+x minio
  - export MINIOD=`pwd`/minio
  - cd -

  # set up mongo
  - cd ..
  - wget http://fastdl.mongodb.org/linux/$MONGODB_VER.tgz
  - tar xfz $MONGODB_VER.tgz
  - export MONGOD=`pwd`/$MONGODB_VER/bin/mongod
  - cd -

   # set up config file
  - export SHOCKEXE=`pwd`/shock_builds/kbase_fork/160815_e9f0e1618e265042bf5cb96429995b5e6ec0a06a/shock-server
  - cp -n test.cfg.example test.cfg
  - sed -i "s#^test.temp.dir =.*#test.temp.dir=temp_test_dir#" test.cfg
  - sed -i "s#^test.mongo.exe.*#test.mongo.exe=$MONGOD#" test.cfg
  - sed -i "s#^test.minio.exe.*#test.minio.exe=$MINIOD#" test.cfg
  - sed -i "s#^test.mongo.wired_tiger.*#test.mongo.wired_tiger=$WIRED_TIGER#" test.cfg
  - sed -i "s#^test.jars.dir.*#test.jars.dir=$JARSDIR#" test.cfg
  - sed -i "s#^test.shock.version.*#test.shock.version=0.9.6#" test.cfg
  - sed -i "s#^test.shock.exe.*#test.shock.exe=$SHOCKEXE#" test.cfg
  - sed -i "s#^test.handleservice.dir.*#test.handleservice.dir=$HSDIR#" test.cfg
  - sed -i "s#^test.sampleservice.dir.*#test.sampleservice.dir=$SAMPLE_DIR#" test.cfg
  - sed -i "s#^test.arango.exe.*#test.arango.exe=$ARANGO_EXE#" test.cfg
  - sed -i "s#^test.arango.js.*#test.arango.js=$ARANGO_JS#" test.cfg
  - cat test.cfg
 
  # run tests
  - ant javadoc
  - export PIPENV_PIPFILE=$(pwd)/python_dependencies/Pipfile
  - pipenv run ant $ANT_TEST

after_success:
  - ls test-reports
  - bash <(curl -s https://codecov.io/bash) -f test-reports/coverage-report.xml

