dist: trusty
sudo: required
language: java
jdk:
  - openjdk8

# TODO split tests into mongo related & non mongo related. Run the former once.
env:
  - MONGODB_VER=mongodb-linux-x86_64-2.6.12 ANT_TEST=test_quick_coverage WIRED_TIGER=false
  - MONGODB_VER=mongodb-linux-x86_64-3.6.10 ANT_TEST=test_quick_coverage WIRED_TIGER=false
  - MONGODB_VER=mongodb-linux-x86_64-3.6.10 ANT_TEST=test_quick_coverage WIRED_TIGER=true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y ant-optional
  - sudo apt-get install -y build-essential python3-pip python3-dev
  - sudo apt-cache search python3.6
  - sudo add-apt-repository -y ppa:jonathonf/python-3.6
  - sudo apt-get -qq update
  - sudo apt-get install python3.6
  - sudo pip3 install sphinx
  - sudo pip3 install jsonrpcbase
  - sudo pip3 install configparser
  - sudo pip3 install pymongo
  - sudo pip3 install cachetools
  - sudo pip3 install uwsgi
  - echo "alias python=python3.6" >> ~/.bash_aliases
  - source ~/.bash_aliases

install:
  - export HOMEDIR=`pwd`
  - cd ..
  - git clone https://github.com/kbase/jars
  - export JARSDIR=`pwd`/jars/lib/jars/
  - export HS_VER=version_1.0.0
  - export HS_COMMIT=f90f1647456d2fd39c7c8b340e6c0727e306bba7
  - export LOG_COMMIT=b549c557e3c519e0a55eadf7863a93db25cd6806
  - git clone -b $HS_VER --single-branch https://github.com/kbase/handle_service2.git
  - cd handle_service2/
  - git reset --hard $HS_COMMIT
  - sudo chmod -R 777 .
  - cd lib/
  - mkdir biokbase
  - cd biokbase/
  - wget https://raw.githubusercontent.com/kbase/sdkbase2/$LOG_COMMIT/log.py
  - cd ..
  - export HSDIR=`pwd`
  - cd $HOMEDIR

script:
  - cd ..
  - wget http://fastdl.mongodb.org/linux/$MONGODB_VER.tgz
  - tar xfz $MONGODB_VER.tgz
  - export MONGOD=`pwd`/$MONGODB_VER/bin/mongod
  - cd -
  - export SHOCKEXE=`pwd`/shock_builds/kbase_fork/160815_e9f0e1618e265042bf5cb96429995b5e6ec0a06a/shock-server
  - cp -n test.cfg.example test.cfg
  - sed -i "s#^test.temp.dir =.*#test.temp.dir=temp_test_dir#" test.cfg
  - sed -i "s#^test.mongo.exe.*#test.mongo.exe=$MONGOD#" test.cfg
  - sed -i "s#^test.mongo.wired_tiger.*#test.mongo.wired_tiger=$WIRED_TIGER#" test.cfg
  - sed -i "s#^test.jars.dir.*#test.jars.dir=$JARSDIR#" test.cfg
  - sed -i "s#^test.shock.version.*#test.shock.version=0.9.6#" test.cfg
  - sed -i "s#^test.shock.exe.*#test.shock.exe=$SHOCKEXE#" test.cfg
  - sed -i "s#^test.handleservice.dir.*#test.handleservice.dir=$HSDIR#" test.cfg
  - cat test.cfg
  - ant javadoc
  - ant $ANT_TEST

after_success:
  - ls test-reports
  - bash <(curl -s https://codecov.io/bash) -f test-reports/coverage-report.xml

